/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserId = IDL.Principal;
export const CenterStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const CollectionCenter = IDL.Record({
  'id' : IDL.Text,
  'status' : CenterStatus,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'contactPerson' : IDL.Text,
  'address' : IDL.Text,
  'mobile' : IDL.Text,
  'assignedPrincipal' : IDL.Opt(UserId),
});
export const CreateBookingRequest = IDL.Record({
  'age' : IDL.Nat,
  'referringDoctor' : IDL.Text,
  'gender' : IDL.Text,
  'patientName' : IDL.Text,
  'testIds' : IDL.Vec(IDL.Text),
  'mobile' : IDL.Text,
});
export const BookingStatus = IDL.Variant({
  'SampleReceived' : IDL.Null,
  'ReportReady' : IDL.Null,
  'Processing' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'age' : IDL.Nat,
  'reportUrl' : IDL.Opt(IDL.Text),
  'status' : BookingStatus,
  'referringDoctor' : IDL.Text,
  'patientId' : IDL.Text,
  'createdAt' : Timestamp,
  'partnerId' : UserId,
  'bookingDate' : Timestamp,
  'gender' : IDL.Text,
  'patientName' : IDL.Text,
  'testIds' : IDL.Vec(IDL.Text),
  'mobile' : IDL.Text,
});
export const CreateCenterRequest = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'contactPerson' : IDL.Text,
  'address' : IDL.Text,
  'mobile' : IDL.Text,
});
export const LabTest = IDL.Record({
  'id' : IDL.Text,
  'mrp' : IDL.Nat,
  'fastingRequired' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sampleType' : IDL.Text,
  'isActive' : IDL.Bool,
  'tubeType' : IDL.Text,
  'reportTime' : IDL.Text,
  'category' : IDL.Text,
  'partnerPrice' : IDL.Nat,
});
export const DashboardSummary = IDL.Record({
  'todaysSamples' : IDL.Nat,
  'totalBookings' : IDL.Nat,
  'reportsPending' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
});
export const UpdateCenterRequest = IDL.Record({
  'status' : CenterStatus,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'contactPerson' : IDL.Text,
  'address' : IDL.Text,
  'mobile' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignCenterPrincipal' : IDL.Func(
      [IDL.Text, UserId],
      [CollectionCenter],
      [],
    ),
  'createBooking' : IDL.Func([CreateBookingRequest], [Booking], []),
  'createCollectionCenter' : IDL.Func(
      [CreateCenterRequest],
      [CollectionCenter],
      [],
    ),
  'createTest' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Text,
        IDL.Text,
      ],
      [LabTest],
      [],
    ),
  'deleteTest' : IDL.Func([IDL.Text], [], []),
  'getAllTests' : IDL.Func([], [IDL.Vec(LabTest)], ['query']),
  'getBooking' : IDL.Func([IDL.Text], [IDL.Opt(Booking)], ['query']),
  'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCollectionCenters' : IDL.Func([], [IDL.Vec(CollectionCenter)], ['query']),
  'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
  'getTests' : IDL.Func([], [IDL.Vec(LabTest)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'trackSample' : IDL.Func([IDL.Text], [IDL.Opt(Booking)], ['query']),
  'updateBookingStatus' : IDL.Func([IDL.Text, BookingStatus], [Booking], []),
  'updateCollectionCenter' : IDL.Func(
      [IDL.Text, UpdateCenterRequest],
      [CollectionCenter],
      [],
    ),
  'updateTest' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [LabTest],
      [],
    ),
  'uploadReport' : IDL.Func([IDL.Text, IDL.Text], [Booking], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const CenterStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const CollectionCenter = IDL.Record({
    'id' : IDL.Text,
    'status' : CenterStatus,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'contactPerson' : IDL.Text,
    'address' : IDL.Text,
    'mobile' : IDL.Text,
    'assignedPrincipal' : IDL.Opt(UserId),
  });
  const CreateBookingRequest = IDL.Record({
    'age' : IDL.Nat,
    'referringDoctor' : IDL.Text,
    'gender' : IDL.Text,
    'patientName' : IDL.Text,
    'testIds' : IDL.Vec(IDL.Text),
    'mobile' : IDL.Text,
  });
  const BookingStatus = IDL.Variant({
    'SampleReceived' : IDL.Null,
    'ReportReady' : IDL.Null,
    'Processing' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'age' : IDL.Nat,
    'reportUrl' : IDL.Opt(IDL.Text),
    'status' : BookingStatus,
    'referringDoctor' : IDL.Text,
    'patientId' : IDL.Text,
    'createdAt' : Timestamp,
    'partnerId' : UserId,
    'bookingDate' : Timestamp,
    'gender' : IDL.Text,
    'patientName' : IDL.Text,
    'testIds' : IDL.Vec(IDL.Text),
    'mobile' : IDL.Text,
  });
  const CreateCenterRequest = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'contactPerson' : IDL.Text,
    'address' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const LabTest = IDL.Record({
    'id' : IDL.Text,
    'mrp' : IDL.Nat,
    'fastingRequired' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sampleType' : IDL.Text,
    'isActive' : IDL.Bool,
    'tubeType' : IDL.Text,
    'reportTime' : IDL.Text,
    'category' : IDL.Text,
    'partnerPrice' : IDL.Nat,
  });
  const DashboardSummary = IDL.Record({
    'todaysSamples' : IDL.Nat,
    'totalBookings' : IDL.Nat,
    'reportsPending' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
  });
  const UpdateCenterRequest = IDL.Record({
    'status' : CenterStatus,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'contactPerson' : IDL.Text,
    'address' : IDL.Text,
    'mobile' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignCenterPrincipal' : IDL.Func(
        [IDL.Text, UserId],
        [CollectionCenter],
        [],
      ),
    'createBooking' : IDL.Func([CreateBookingRequest], [Booking], []),
    'createCollectionCenter' : IDL.Func(
        [CreateCenterRequest],
        [CollectionCenter],
        [],
      ),
    'createTest' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Text,
          IDL.Text,
        ],
        [LabTest],
        [],
      ),
    'deleteTest' : IDL.Func([IDL.Text], [], []),
    'getAllTests' : IDL.Func([], [IDL.Vec(LabTest)], ['query']),
    'getBooking' : IDL.Func([IDL.Text], [IDL.Opt(Booking)], ['query']),
    'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCollectionCenters' : IDL.Func(
        [],
        [IDL.Vec(CollectionCenter)],
        ['query'],
      ),
    'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
    'getTests' : IDL.Func([], [IDL.Vec(LabTest)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'trackSample' : IDL.Func([IDL.Text], [IDL.Opt(Booking)], ['query']),
    'updateBookingStatus' : IDL.Func([IDL.Text, BookingStatus], [Booking], []),
    'updateCollectionCenter' : IDL.Func(
        [IDL.Text, UpdateCenterRequest],
        [CollectionCenter],
        [],
      ),
    'updateTest' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [LabTest],
        [],
      ),
    'uploadReport' : IDL.Func([IDL.Text, IDL.Text], [Booking], []),
  });
};

export const init = ({ IDL }) => { return []; };