/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : string,
  'age' : bigint,
  'reportUrl' : [] | [string],
  'status' : BookingStatus,
  'referringDoctor' : string,
  'patientId' : string,
  'createdAt' : Timestamp,
  'partnerId' : UserId,
  'bookingDate' : Timestamp,
  'gender' : string,
  'patientName' : string,
  'testIds' : Array<string>,
  'mobile' : string,
}
export type BookingStatus = { 'SampleReceived' : null } |
  { 'ReportReady' : null } |
  { 'Processing' : null } |
  { 'Pending' : null };
export type CenterStatus = { 'active' : null } |
  { 'inactive' : null };
export interface CollectionCenter {
  'id' : string,
  'status' : CenterStatus,
  'city' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'contactPerson' : string,
  'address' : string,
  'mobile' : string,
  'assignedPrincipal' : [] | [UserId],
}
export interface CreateBookingRequest {
  'age' : bigint,
  'referringDoctor' : string,
  'gender' : string,
  'patientName' : string,
  'testIds' : Array<string>,
  'mobile' : string,
}
export interface CreateCenterRequest {
  'city' : string,
  'name' : string,
  'contactPerson' : string,
  'address' : string,
  'mobile' : string,
}
export interface DashboardSummary {
  'todaysSamples' : bigint,
  'totalBookings' : bigint,
  'reportsPending' : bigint,
  'totalRevenue' : bigint,
}
export interface LabTest {
  'id' : string,
  'mrp' : bigint,
  'fastingRequired' : boolean,
  'name' : string,
  'description' : string,
  'sampleType' : string,
  'isActive' : boolean,
  'tubeType' : string,
  'reportTime' : string,
  'category' : string,
  'partnerPrice' : bigint,
}
export type Timestamp = bigint;
export interface UpdateCenterRequest {
  'status' : CenterStatus,
  'city' : string,
  'name' : string,
  'contactPerson' : string,
  'address' : string,
  'mobile' : string,
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignCenterPrincipal' : ActorMethod<[string, UserId], CollectionCenter>,
  'createBooking' : ActorMethod<[CreateBookingRequest], Booking>,
  'createCollectionCenter' : ActorMethod<
    [CreateCenterRequest],
    CollectionCenter
  >,
  'createTest' : ActorMethod<
    [string, string, bigint, bigint, string, string, boolean, string, string],
    LabTest
  >,
  'deleteTest' : ActorMethod<[string], undefined>,
  'getAllTests' : ActorMethod<[], Array<LabTest>>,
  'getBooking' : ActorMethod<[string], [] | [Booking]>,
  'getBookings' : ActorMethod<[], Array<Booking>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCollectionCenters' : ActorMethod<[], Array<CollectionCenter>>,
  'getDashboardSummary' : ActorMethod<[], DashboardSummary>,
  'getTests' : ActorMethod<[], Array<LabTest>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'trackSample' : ActorMethod<[string], [] | [Booking]>,
  'updateBookingStatus' : ActorMethod<[string, BookingStatus], Booking>,
  'updateCollectionCenter' : ActorMethod<
    [string, UpdateCenterRequest],
    CollectionCenter
  >,
  'updateTest' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      bigint,
      string,
      string,
      boolean,
      string,
      string,
      boolean,
    ],
    LabTest
  >,
  'uploadReport' : ActorMethod<[string, string], Booking>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];