/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface CreateBookingRequest {
    age: bigint;
    referringDoctor: string;
    gender: string;
    patientName: string;
    testIds: Array<string>;
    mobile: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface CollectionCenter {
    id: string;
    status: CenterStatus;
    city: string;
    name: string;
    createdAt: Timestamp;
    contactPerson: string;
    address: string;
    mobile: string;
    assignedPrincipal?: UserId;
}
export interface LabTest {
    id: string;
    mrp: bigint;
    fastingRequired: boolean;
    name: string;
    description: string;
    sampleType: string;
    isActive: boolean;
    tubeType: string;
    reportTime: string;
    category: string;
    partnerPrice: bigint;
}
export interface DashboardSummary {
    todaysSamples: bigint;
    totalBookings: bigint;
    reportsPending: bigint;
    totalRevenue: bigint;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UpdateCenterRequest {
    status: CenterStatus;
    city: string;
    name: string;
    contactPerson: string;
    address: string;
    mobile: string;
}
export type UserId = Principal;
export interface CreateCenterRequest {
    city: string;
    name: string;
    contactPerson: string;
    address: string;
    mobile: string;
}
export interface Booking {
    id: string;
    age: bigint;
    reportUrl?: string;
    status: BookingStatus;
    referringDoctor: string;
    patientId: string;
    createdAt: Timestamp;
    partnerId: UserId;
    bookingDate: Timestamp;
    gender: string;
    patientName: string;
    testIds: Array<string>;
    mobile: string;
}
export enum BookingStatus {
    SampleReceived = "SampleReceived",
    ReportReady = "ReportReady",
    Processing = "Processing",
    Pending = "Pending"
}
export enum CenterStatus {
    active = "active",
    inactive = "inactive"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignCenterPrincipal(centerId: string, partnerPrincipal: UserId): Promise<CollectionCenter>;
    createBooking(req: CreateBookingRequest): Promise<Booking>;
    createCollectionCenter(req: CreateCenterRequest): Promise<CollectionCenter>;
    createTest(name: string, category: string, mrp: bigint, partnerPrice: bigint, sampleType: string, tubeType: string, fastingRequired: boolean, reportTime: string, description: string): Promise<LabTest>;
    deleteTest(id: string): Promise<void>;
    getAllTests(): Promise<Array<LabTest>>;
    getBooking(id: string): Promise<Booking | null>;
    getBookings(): Promise<Array<Booking>>;
    getCallerUserRole(): Promise<UserRole>;
    getCollectionCenters(): Promise<Array<CollectionCenter>>;
    getDashboardSummary(): Promise<DashboardSummary>;
    getTests(): Promise<Array<LabTest>>;
    isCallerAdmin(): Promise<boolean>;
    trackSample(patientIdOrMobile: string): Promise<Booking | null>;
    updateBookingStatus(id: string, status: BookingStatus): Promise<Booking>;
    updateCollectionCenter(id: string, req: UpdateCenterRequest): Promise<CollectionCenter>;
    updateTest(id: string, name: string, category: string, mrp: bigint, partnerPrice: bigint, sampleType: string, tubeType: string, fastingRequired: boolean, reportTime: string, description: string, isActive: boolean): Promise<LabTest>;
    uploadReport(bookingId: string, reportUrl: string): Promise<Booking>;
}
import type { Booking as _Booking, BookingStatus as _BookingStatus, CenterStatus as _CenterStatus, CollectionCenter as _CollectionCenter, Timestamp as _Timestamp, UpdateCenterRequest as _UpdateCenterRequest, UserId as _UserId, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCenterPrincipal(arg0: string, arg1: UserId): Promise<CollectionCenter> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCenterPrincipal(arg0, arg1);
                return from_candid_CollectionCenter_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCenterPrincipal(arg0, arg1);
            return from_candid_CollectionCenter_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async createBooking(arg0: CreateBookingRequest): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0);
                return from_candid_Booking_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0);
            return from_candid_Booking_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCollectionCenter(arg0: CreateCenterRequest): Promise<CollectionCenter> {
        if (this.processError) {
            try {
                const result = await this.actor.createCollectionCenter(arg0);
                return from_candid_CollectionCenter_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCollectionCenter(arg0);
            return from_candid_CollectionCenter_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTest(arg0: string, arg1: string, arg2: bigint, arg3: bigint, arg4: string, arg5: string, arg6: boolean, arg7: string, arg8: string): Promise<LabTest> {
        if (this.processError) {
            try {
                const result = await this.actor.createTest(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTest(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async deleteTest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTest(arg0);
            return result;
        }
    }
    async getAllTests(): Promise<Array<LabTest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTests();
            return result;
        }
    }
    async getBooking(arg0: string): Promise<Booking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookings();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookings();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCollectionCenters(): Promise<Array<CollectionCenter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollectionCenters();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollectionCenters();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardSummary(): Promise<DashboardSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardSummary();
            return result;
        }
    }
    async getTests(): Promise<Array<LabTest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTests();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async trackSample(arg0: string): Promise<Booking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.trackSample(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trackSample(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBookingStatus(arg0: string, arg1: BookingStatus): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n25(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Booking_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n25(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Booking_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCollectionCenter(arg0: string, arg1: UpdateCenterRequest): Promise<CollectionCenter> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCollectionCenter(arg0, to_candid_UpdateCenterRequest_n27(this._uploadFile, this._downloadFile, arg1));
                return from_candid_CollectionCenter_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCollectionCenter(arg0, to_candid_UpdateCenterRequest_n27(this._uploadFile, this._downloadFile, arg1));
            return from_candid_CollectionCenter_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTest(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: string, arg6: string, arg7: boolean, arg8: string, arg9: string, arg10: boolean): Promise<LabTest> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTest(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTest(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
            return result;
        }
    }
    async uploadReport(arg0: string, arg1: string): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadReport(arg0, arg1);
                return from_candid_Booking_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadReport(arg0, arg1);
            return from_candid_Booking_n15(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BookingStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_CenterStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CenterStatus): CenterStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_CollectionCenter_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CollectionCenter): CollectionCenter {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Booking]): Booking | null {
    return value.length === 0 ? null : from_candid_Booking_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _CenterStatus;
    city: string;
    name: string;
    createdAt: _Timestamp;
    contactPerson: string;
    address: string;
    mobile: string;
    assignedPrincipal: [] | [_UserId];
}): {
    id: string;
    status: CenterStatus;
    city: string;
    name: string;
    createdAt: Timestamp;
    contactPerson: string;
    address: string;
    mobile: string;
    assignedPrincipal?: UserId;
} {
    return {
        id: value.id,
        status: from_candid_CenterStatus_n12(_uploadFile, _downloadFile, value.status),
        city: value.city,
        name: value.name,
        createdAt: value.createdAt,
        contactPerson: value.contactPerson,
        address: value.address,
        mobile: value.mobile,
        assignedPrincipal: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.assignedPrincipal))
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    age: bigint;
    reportUrl: [] | [string];
    status: _BookingStatus;
    referringDoctor: string;
    patientId: string;
    createdAt: _Timestamp;
    partnerId: _UserId;
    bookingDate: _Timestamp;
    gender: string;
    patientName: string;
    testIds: Array<string>;
    mobile: string;
}): {
    id: string;
    age: bigint;
    reportUrl?: string;
    status: BookingStatus;
    referringDoctor: string;
    patientId: string;
    createdAt: Timestamp;
    partnerId: UserId;
    bookingDate: Timestamp;
    gender: string;
    patientName: string;
    testIds: Array<string>;
    mobile: string;
} {
    return {
        id: value.id,
        age: value.age,
        reportUrl: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.reportUrl)),
        status: from_candid_BookingStatus_n18(_uploadFile, _downloadFile, value.status),
        referringDoctor: value.referringDoctor,
        patientId: value.patientId,
        createdAt: value.createdAt,
        partnerId: value.partnerId,
        bookingDate: value.bookingDate,
        gender: value.gender,
        patientName: value.patientName,
        testIds: value.testIds,
        mobile: value.mobile
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): CenterStatus {
    return "active" in value ? CenterStatus.active : "inactive" in value ? CenterStatus.inactive : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    SampleReceived: null;
} | {
    ReportReady: null;
} | {
    Processing: null;
} | {
    Pending: null;
}): BookingStatus {
    return "SampleReceived" in value ? BookingStatus.SampleReceived : "ReportReady" in value ? BookingStatus.ReportReady : "Processing" in value ? BookingStatus.Processing : "Pending" in value ? BookingStatus.Pending : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CollectionCenter>): Array<CollectionCenter> {
    return value.map((x)=>from_candid_CollectionCenter_n10(_uploadFile, _downloadFile, x));
}
function to_candid_BookingStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_CenterStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CenterStatus): _CenterStatus {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateCenterRequest_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateCenterRequest): _UpdateCenterRequest {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: CenterStatus;
    city: string;
    name: string;
    contactPerson: string;
    address: string;
    mobile: string;
}): {
    status: _CenterStatus;
    city: string;
    name: string;
    contactPerson: string;
    address: string;
    mobile: string;
} {
    return {
        status: to_candid_CenterStatus_n29(_uploadFile, _downloadFile, value.status),
        city: value.city,
        name: value.name,
        contactPerson: value.contactPerson,
        address: value.address,
        mobile: value.mobile
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    SampleReceived: null;
} | {
    ReportReady: null;
} | {
    Processing: null;
} | {
    Pending: null;
} {
    return value == BookingStatus.SampleReceived ? {
        SampleReceived: null
    } : value == BookingStatus.ReportReady ? {
        ReportReady: null
    } : value == BookingStatus.Processing ? {
        Processing: null
    } : value == BookingStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CenterStatus): {
    active: null;
} | {
    inactive: null;
} {
    return value == CenterStatus.active ? {
        active: null
    } : value == CenterStatus.inactive ? {
        inactive: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
